

 development:
   adapter: postgresql
   encoding: unicode
   database: cart_development
   pool: 5
   username: cart_development
   password: cart_development

 test:
   adapter: postgresql
   encoding: unicode
   database: cart_test
   pool: 5
   username: cart_test
   password: cart_test
