development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: cart_development
  pool: 5
  user: cart_development
  password: cart_development

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: cart_test
  pool: 5
  user: cart_test
  password: cart_test
